name: Request Unity Activation File

on: 
  workflow_dispatch:

jobs:
  activation:
    name: Request .alf
    runs-on: ubuntu-latest
    steps:
      - name: Request activation File
        id: get-alf 
        uses: game-ci/unity-request-activation-file@v2

      - name: Upload activation file
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Activation-File
          path: ${{ steps.get-alf.outputs.filePath }}   
          retention-days: 1